### PR TITLE
Blueflood performance issues

### PR DESCRIPTION
**Pull request by ChandraAddala**
- Improvements to call new blueflood API /metric_name/search
  - changed tests accordingly

### CODE REVIEW

**Comment by ChandraAddala** [comment]
ok to test

**Comment by ChandraAddala** [comment]
retest this please

**Comment by VinnyQ** [comment]
@ChandraAddala I commit a new file called .travis.yml to the master branch.  Fetch that and merge it to your PR and try again to see if the PR will trigger a build for it.

**Comment by ChandraAddala** [comment]
@VinnyQ Build got triggered. Thx.

**Comment by ChandraAddala** [comment]
But it looked like it triggered 5 jobs. Whats up with that?

**Comment by VinnyQ** [comment]
Could be the way I setup the env variable on travis-ci.org it looks like.  I cleaned it up so let's try it again.

ok to test

**Comment by VinnyQ** [comment]
ok looks like i setup the .travis.yml wrong.  -env is not environmental variable!

**Comment by VinnyQ** [comment]
ok this should be fixed.  You should rebase from master and push -f

**Pull request merged**
